services:
  kapibarabot:
    container_name: kapibarabot
    restart: unless-stopped
    build: .
    volumes:
      - db-data:${SQLITE_DB}
    environment:
      - AIRTABLE_TOKEN=${AIRTABLE_TOKEN}
      - TG_TOKEN=${TG_TOKEN}
      - AO3_LOGIN=${AO3_LOGIN}
      - AO3_PASSWORD=${AO3_PASSWORD}
      - CHAT_IDS=${CHAT_IDS}
      - SENDER_EMAIL=${SENDER_EMAIL}
      - KINDLE_EMAIL=${KINDLE_EMAIL}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - FICS_TEMP_PATH=${FICS_TEMP_PATH}
volumes:
    db-data:
