services:
  kapibarabot:
    container_name: kapibarabot
    restart: unless-stopped
    build: .
    volumes:
      - ao3-db:${DB_PATH}
    environment:
      - TG_TOKEN=${TG_TOKEN}
      - AO3_LOGIN=${AO3_LOGIN}
      - AO3_PASSWORD=${AO3_PASSWORD}
      - ALLOWED_CHATS=${ALLOWED_CHATS}
      - MY_CHAT_ID=${MY_CHAT_ID}
      - SENDER_EMAIL=${SENDER_EMAIL}
      - SENDER_PASSWORD=${SENDER_PASSWORD}
      - FICS_TEMP_PATH=${FICS_TEMP_PATH}
      - DB_PATH=${DB_PATH}
volumes:
  ao3-db:
    external: true
